### ISSUE TITLE
Hangouts-chat can't work in proxy environment

### ISSUE THREAD

**Issue by komatsuyuji** [enzinia/hangouts-chat#2]
We want to use Gitlab's Hangouts Chat Service, but it can not work in proxy environment.
So we checked hangouts-chat's source code. and found that hangouts-chat does not support proxy.
We hope that you can add proxy function into the source code.
For example,
```
diff lib/hangouts_chat/http.rb lib/hangouts_chat/http.rb.org 
25c25
<         res = Net::HTTP.start(@uri.hostname, @uri.port, :ENV, use_ssl: true) do |http|
---
>         res = Net::HTTP.start(@uri.hostname, @uri.port, use_ssl: true) do |http|
```
Thanks!

**Comment by enzinia** [comment]
@komatsuyuji Sorry for the inconvenience and long response.

Thank you very much for the problem report and even suggested solution!
Added your fix into version 0.0.6.

Please note that to use it in `gitlab.com` need to create MR to update `Gemfile.lock` to use version 0.0.6 of this gem.
